# Generated by Django 2.2.19 on 2021-04-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0259_depr_program_card_image_url_and_add_exec_ed_cert_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathway',
            name='lms_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
