# Generated by Django 2.2.19 on 2021-06-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0260_pathway_lms_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprogram',
            name='rice_subject_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='rice_subject_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
